FROM ubi8/ubi:8.3

MAINTAINER Bhuban

ARG NEXUS_VERSION=2.14.3-02
ENV NEXUS_HOME=/opt/nexus

RUN yum install -y java-1.8.0-openjdk-devel.x86_64 && yum clean all

RUN groupadd -r nexus -f -g 1001 && \
    useradd -u 1001 -r -g nexus -m -d ${NEXUS_HOME} -s /sbin/nologin -c "Nexus User" nexus && \
    chmod  -R 775 ${NEXUS_HOME} && \
    chown -R nexus:nexus ${NEXUS_HOME}


USER nexus
ADD nexus-2.14.3-02-bundle.tar.gz  ${NEXUS_HOME}/
COPY nexus-start.sh  ${NEXUS_HOME}/nexus-start.sh

RUN ln -s ${NEXUS_HOME}/nexus-${NEXUS_VERSION} ${NEXUS_HOME}/nexus2

WORKDIR ${NEXUS_HOME}

VOLUME ["/opt/nexus/sonatype-work]


CMD ["sh", "nexus-start.sh"]

